[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Clara Bacciu", email = "clara.bacciu@gmail.com"},
]
dependencies = [
    "shapely>=2.0.1",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

